### ISSUE TITLE
Occassionally failing to connect to ophyd-async devices

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/hyperion#1164]
We're getting occasional failures to connect to ophyd_async devices of the form:
```
[2024-02-19 12:57:34,276] Hyperion __main__ ERROR: ['Traceback (most recent call last):\n', '  File "/dls_sw/i03/software/bluesky/hyperion_v8.9.0/hyperion/src/hyperion/__main__.py", line 235, in put\n    status_and_message = self.runner.start(\n', '  File "/dls_sw/i03/software/bluesky/hyperion_v8.9.0/hyperion/src/hyperion/__main__.py", line 108, in start\n    devices: Any = PLAN_REGISTRY[plan_name]["setup"](self.context)\n', '  File "/dls_sw/i03/software/bluesky/hyperion_v8.9.0/hyperion/src/hyperion/experiment_plans/rotation_scan_plan.py", line 75, in create_devices\n    return device_composite_from_context(context, RotationScanComposite)\n', '  File "/dls_sw/i03/software/bluesky/hyperion_v8.9.0/hyperion/src/hyperion/utils/context.py", line 70, in device_composite_from_context\n    _wait_for_connection(device=device)\n', '  File "/dls_sw/i03/software/bluesky/hyperion_v8.9.0/dodal/src/dodal/beamlines/beamline_utils.py", line 54, in _wait_for_connection\n    call_in_bluesky_event_loop(\n', '  File "/dls_sw/i03/software/bluesky/hyperion_v8.9.0/hyperion/.venv/lib/python3.10/site-packages/bluesky/run_engine.py", line 2735, in call_in_bluesky_event_loop\n    return fut.result(timeout=timeout)\n', '  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/concurrent/futures/_base.py", line 460, in result\n    raise TimeoutError()\n', 'concurrent.futures._base.TimeoutError\n']
```
This is particularly frustrated as we're re-connecting to `ophyd-async` devices on each run of the plan rather than just at startup for `ophyd` devices and the error message out of ophyd-async is still poor.

## Acceptance Criteria
* We only connect once at startup

**Comment by DominicOram** [comment]
Closing as duplicate of https://github.com/DiamondLightSource/hyperion/issues/1159
