### ISSUE TITLE
Cannot tigger robot_load with new hyperion params

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/hyperion#1348]
Under the v9.2.1 currently on the beamlien, when trying to trigger the robot load with:
```
		hyperion_params = {
			"parameter_model_version": HYPERION_PARAM_VERSION,
			"visit": visit,
			"file_name": prefix,
			"demand_energy_ev": requested_energy_ev,
			"detector_distance_mm": detector_distance,
			"sample_id": 0,
			"sample_puck":  sample_reference.getContainer_reference(),
			"sample_pin": sample_reference.getSample_location(),
			"storage_directory": directory,
			"zocalo_environment": "artemis",
			"exposure_time_s": 0.004,
			"omega_start_deg": 0,
			"use_roi_mode": True,
			"transmission_frac": 1.0,
			"ispyb_extras": {
				"beam_size_x": real_beam_size_x/1000.0,
				"beam_size_y": real_beam_size_y/1000.0,
				"focal_spot_size_x": focal_spot_size_x,
				"focal_spot_size_y": focal_spot_size_y,
				"position": list(current_position),
				},
			}
```
We get the following error:
```
Traceback (most recent call last):
  File "/dls_sw/i03/software/bluesky/hyperion_v9.2.1/hyperion/.venv/lib/python3.11/site-packages/bluesky/run_engine.py", line 1547, in _run
    msg = self._plan_stack[-1].send(resp)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i03/software/bluesky/hyperion_v9.2.1/hyperion/src/hyperion/experiment_plans/robot_load_then_centre_plan.py", line 229, in robot_load_then_centre
    parameters = parameters.old_parameters()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i03/software/bluesky/hyperion_v9.2.1/hyperion/src/hyperion/parameters/gridscan.py", line 174, in old_parameters
    return RobotLoadThenCentreInternalParameters(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1074, in pydantic.main.validate_model
  File "pydantic/fields.py", line 864, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 1154, in pydantic.fields.ModelField._apply_validators
  File "pydantic/class_validators.py", line 306, in pydantic.class_validators._generic_validator_cls.lambda5
  File "/dls_sw/i03/software/bluesky/hyperion_v9.2.1/hyperion/src/hyperion/parameters/plan_specific/robot_load_then_center_params.py", line 108, in _preprocess_hyperion_params
    return RobotLoadThenCentreHyperionParameters(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1074, in pydantic.main.validate_model
  File "pydantic/fields.py", line 881, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 1098, in pydantic.fields.ModelField._validate_singleton
  File "pydantic/fields.py", line 1154, in pydantic.fields.ModelField._apply_validators
  File "pydantic/class_validators.py", line 337, in pydantic.class_validators._generic_validator_basic.lambda13
  File "pydantic/main.py", line 711, in pydantic.main.BaseModel.validate
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1048, in pydantic.main.validate_model
  File "/dls_sw/i03/software/bluesky/hyperion_v9.2.1/dodal/src/dodal/devices/detector/detector.py", line 57, in create_beamxy_and_runnumber
    values["det_dist_to_beam_converter_path"]
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'det_dist_to_beam_converter_path'
```

## Acceptance Criteria
* We can trigger a robot load plan from GDA

**Comment by DominicOram** [comment]
Plan is to wait for https://github.com/DiamondLightSource/hyperion/pull/1353 to be merged, do a new release and work based on that
