### ISSUE TITLE
Testing v9.5.2

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/hyperion#1514]
* `confluent-kafka` not installing on the control machine. Fixed by just installing this from the workstation (so it's the wrong binaries) then doing the rest of the install from the control machine
* Was no `dodal` release so just checked out main?
* GDA still doing xrc when robot load enabled
*

**Comment by DominicOram** [comment]
* Issue with PCAP writing in that we had to `stage` the panda after we run setup
* Need to get the aperture positions for moving before snapshot from the aperture scatterguard itself - need to probably have an enum with the positions in that we use that as an external interface
* Issue with gda not knowing the sample on restart and so sending an empty sample id to hyperion
``` [31m[E 240808 14:33:41.263 __main__:254] ['Traceback (most recent call last):\n', '  File "/dls_sw/i03/software/bluesky/hyperion_v9.5.2/hyperion/src/hyperion/__main__.py", line 228, in compose_start_args\n    parameters = experiment_internal_param_type(**json.loads(request.data))\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__\n', 'pydantic.error_wrappers.ValidationError: 1 validation error for PinTipCentreThenXrayCentre\nsample_id\n  none is not an allowed value (type=type_error.none.not_allowed)\n', '\nThe above exception was the direct cause of the following exception:\n\n', 'Traceback (most recent call last):\n', '  File "/dls_sw/i03/software/bluesky/hyperion_v9.5.2/hyperion/src/hyperion/__main__.py", line 246, in put\n    plan, params, plan_name, callback_type = compose_start_args(\n                                             ^^^^^^^^^^^^^^^^^^^\n', '  File "/dls_sw/i03/software/bluesky/hyperion_v9.5.2/hyperion/src/hyperion/__main__.py", line 230, in compose_start_args\n    raise ValueError(\n', "ValueError: Supplied parameters don't match the plan for this endpoint\n"][0m```

**Comment by DominicOram** [comment]
* https://ispyb.diamond.ac.uk/samples/sid/5682018 is the full hyperion doing everything
* Pulse size on PCAP needs to be the same as the exposure time
* Box size isn't just changed by changing `BOX_WIDTH_UM` because it isn't passed through to `grid_detection_plan`. Trying to add 10 in that call resulted in https://ispyb.diamond.ac.uk/dc/visit/cm37235-3/dcg/12681792 , which failed to kickoff the FGS
